### ISSUE TITLE
Invalid nginx configuration

### ISSUE THREAD

**Issue by spamguy** [eustasy/letsencrypt-with-nginx#3]
The nginx configuration in this repo isn't valid when loaded into my copy of nginx (Ubuntu 14.04, v1.9.7). It complains:
```
nginx: [emerg] duplicate listen options for [::]:443 in /etc/nginx/conf.d/diplio.conf:21
```
I'm mostly an nginx n00b still, but at first glance I would agree with it: the second server block clashes with the third. Commenting out the second block works, and pages are served as expected.

(To be clear, this is with one server environment, unlike ticket #2.)

**Comment by lewisgoddard** [comment]
I have cleared this, it was because I was setting `ipv6only=on` for each port, when it can only be set once. Since it's on by default, I have removed it.
